---
# tasks file for stackhpc.firewallgen

- name: gen firewall
  template:
    src: firewall-rules.j2
    dest: "{{ firewallgen_rules_path }}"
  tags: template

- name: backup original rules
  shell: iptables-save > "{{ firewallgen_backup_path }}"
  args:
    creates: "{{ firewallgen_backup_path }}"
  become: True

- name: clean up old rules
  include_tasks: delete.yml
  tags: always

- name: load firewall rules
  # -n option will not flush existing rules
  shell:
    iptables-restore -n < "{{ firewallgen_rules_path }}"
  become: True

- include_tasks: persist.yml
  when: firewall_action == "apply"
