---
# This will set the default policy of the INPUT and OUTPUT Chains to ACCEPT

- name: Delete old iptables rules
  hosts: all
  vars:
    tables:
      - filter
      - nat
      - mangle
      - raw
      - security
  tasks:
    - name: Get list of chains for a given table
      shell: iptables -L -t {{ item }} | grep "^Chain " | awk '{print $2}'
      with_items: "{{ tables }}"
      register: chains
    - name: create table to chain map
      set_fact:
        table_to_chains: "{{ table_to_chains | default({}) | combine({item[0] : item[1].stdout_lines}) }}"
      with_together:
        - "{{ tables }}"
        - "{{ chains.results }}"
    - name: Set default policy of ACCEPT to input chain
      iptables:
        chain: INPUT
        policy: ACCEPT
    - name: Set default policy of ACCEPT to output chain
      iptables:
        chain: OUTPUT
        policy: ACCEPT
    - name: delete old rules
      include_tasks: remove-rules.yml
      with_items: "{{ tables }}"
      loop_control:
        loop_var: table


