---

- name: install virtualenv
  package:
    name:
      - python-virtualenv
      - git
    state: present
  become: True
- name: Set up virtualenv
  pip:
    name:
      - git+https://github.com/jovial/firewallgen
      - jinja2 
    virtualenv: /tmp/venv/firewallgen

- name: Set fact containing default interface map
  set_fact:
    default_network_map:
      '127.0.0.1': 'lo'

- name: network_interface_map
  set_fact:
    ip_map: "{{ ip_map | default(default_network_map) | combine({item | net_ip : '{{ ' ~ item ~ '_interface }}'})}}"
  with_items: "{{ network_interfaces }}"

- debug:
    msg: "{{ ip_map }}"

- name: run firewallgen
  vars:
    ansible_python_interpreter: /tmp/venv/firewallgen/bin/python
  firewallgen:
    ip_to_interface_map: "{{ ip_map }}"
    ip_version: 4
  register: firewallgen
  become: True

- name: make sure output directory exists
  file:
    path: "{{ firewallgen_output_path }}"
    state: directory
  delegate_to: localhost

- name: output template
  vars:
    firewall_rules: "{{ firewallgen.sockets }}"
  template:
    src: sockets-to-rules.j2
    dest: "{{ firewallgen_output_path ~ '/' ~ inventory_hostname }}"
  delegate_to: localhost

- name: dump test output
  debug:
    msg: '{{ firewallgen.sockets }}'
