---

- name: install virtualenv
  package:
    name:
      - python-virtualenv
      - git
    state: present
  become: True
- name: Set up virtualenv
  pip:
    name:
      - git+https://github.com/jovial/firewallgen
      - jinja2 
    virtualenv: /tmp/venv/firewallgen

- name: Set fact containing default interface map
  set_fact:
    default_network_map:
      '127.0.0.1': 'lo'

- name: get virtual interfaces address map
  set_fact:
    vip_addresses:  "{{ vip_addresses | default({}) | combine({ vip: item }) }}"
  vars:
    vip: "{{ item | net_vip_address }}"
  when: vip | default(False, True)
  with_items: "{{ network_interfaces }}"

- name: register vip_reverse_map default value
  set_fact:
    vip_reverse_map: {}

- name: register vip_reverse_map
  set_fact:
    vip_reverse_map:  "{{ vip_reverse_map  | combine({ vip: value }) }}"
  vars:
    vip: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items: "{{ firewallgen_vip_map }}"

- name: network_interface_map
  set_fact:
    ip_map: "{{ ip_map | default({}) | combine({item | net_ip : item })}}"
  with_items: "{{ network_interfaces }}"

- name: Combine virtual and default maps
  set_fact:
    network_allocations: "{{ vip_addresses | combine(ip_map) }}" 

- name: ip_reverse_map
  set_fact:
    ip_reverse_map: "{{ firewallgen_ip_map | keyvalue_dict }}"

- debug:
    msg: "{{ network_allocations }}"

- name: vip reverse map
  debug:
    msg: "{{ vip_reverse_map }}"

- name: ip reverse map
  debug:
    msg: "{{ ip_reverse_map }}"

- name: run firewallgen
  vars:
    ansible_python_interpreter: /tmp/venv/firewallgen/bin/python
  firewallgen:
    ip_to_interface_map: "{{ default_network_map }}"
    ip_version: 4
  register: firewallgen
  become: True

- name: make sure output directory exists
  file:
    path: "{{ firewallgen_output_path }}"
    state: directory
  delegate_to: localhost

- name: set initial value for sockets_rewrite
  # need to set this in case of no rewrite rules
  set_fact:
    sockets_rewrite: "{{ firewallgen.sockets }}"

- name: rewrite sockets
  set_fact:
    sockets_rewrite: "{{ sockets_rewrite | to_json | jq(item) }}"
  with_items: "{{ firewallgen_ipv4_input_allow_rewrite_rules }}"

- name: write out sockets before rewriting 
  shell:
    cmd: |
      cat <<EOF > /tmp/firewallgen-sockets
      {{ firewallgen.sockets | to_json }}
      EOF
  when: debug | default(False)

- name: write out sockets after rewriting
  shell:
    cmd: |
      cat <<EOF > /tmp/firewallgen-sockets-rewrite
      {{ sockets_rewrite | to_json }}
      EOF
  when: debug | default(False)

- name: rewrite network ip
  set_fact:
    sockets_network_rewrite: "{{ sockets_network_rewrite | default([]) + [(item | combine({'ip': network_ip, 'interface': interface}))] }}"
  vars:
    dest: "{{ item['ip'] }}"
    interface: "{% if dest in network_allocations %}{{ '{{ ' ~ network_allocations[dest] ~ '_interface }}'}}{% else %}{{item['interface']}}{% endif %}"
    network_ip: "{% if dest in ip_reverse_map %}{{ '{{ ' ~ ip_reverse_map[dest] ~ ' | net_ip }}' }}{% elif dest in vip_reverse_map %}{{ '{{ ' ~ vip_reverse_map[dest] ~ ' | net_vip_address }}'}}{% else %}{{ dest }}{% endif %}"
  when: dest != None
  with_items: "{{ sockets_rewrite }}"

- name: output template
  vars:
    firewall_rules: "{{ sockets_network_rewrite | sort_multi('proto', 'interface', 'port', 'ip') }}"
  template:
    src: sockets-to-rules.j2
    dest: "{{ firewallgen_output_path ~ '/' ~ inventory_hostname }}"
  delegate_to: localhost

