---

- block:
  - name: install package for persistent iptables
    package:
      name: iptables-services

  - name: enable service to load iptables rules on boot
    service:
      name:  iptables
      state: started
      enabled: True

  - name: persist the rules
    command: /usr/libexec/iptables/iptables.init save
  become: True
  when: ansible_os_family == "RedHat"
