---

- name: collect rules to remove
  # This returns a rule number for each rule with a comment starting: "FIREWALLGEN"
  shell: iptables -L {{ item }} -t {{ table }} --line-numbers | grep '/\* FIREWALLGEN.*\*/' | grep -o '^[[:digit:]]*\>'
  with_items: "{{ table_to_chains[table] }}"
  register: rules_to_remove
  become: True
  failed_when: False

- name: remove rule
  include_tasks:
    remove-rule.yml
  with_together:
    - "{{ table_to_chains[table] }}"
    - "{{ rules_to_remove.results }}"
  loop_control:
    loop_var: chain_rules
  vars:
    chain: "{{ chain_rules[0] }}"
    stale_rules: "{{ chain_rules[1].stdout_lines }}"

